### ISSUE TITLE
Hoofdstuk: extra informatie

### ISSUE THREAD

**Issue by fhb1990** [Geonovum/inspire-wiki#12]
Vermoedelijk staat hier ook veel verouderde informatie in, of kan er een hoop aan worden toegevoegd.

**Comment by wboersma** [comment]
Ik heb hoofdstuk extra informatie herschreven. Terminologie weggehaald (stond deels al in hoofstuk 1). ISO en OGC iets uitgebreid en UML verder laten staan.
