### ISSUE TITLE
paragraaf 3.5 https://geonovum.github.io/inspire-wiki/#prioritaire-datasets-e-reporting

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/inspire-wiki#17]
Alle sub-issues in https://github.com/Geonovum/inspire-wiki/issues/7 zijn verwerkt behalve deze:

@Wideke, kun jij voor onderstaande de tekst aanvullen en juiste verwijzing doen?

4.5 Prioritaire datasets (e-reporting).
-Dit stuk aanvullen met de nieuwe ontwikkelingen en verwijzen naar de nieuwe actie: https://webgate.ec.europa.eu/fpfis/wikis/display/InspireMIG/Action+2.1+Need-driven+data+prioritisation
-PB: Wat wordt bedoeld met "en voor as-is versus nieuwe datasets"?
-PB: Huidige link achter JRC linkt door naar Inspire helpdesk. Waar naartoe aanpassen?
-Freek Boersma: 'Prioritaire datasets' kan een inleiding gebruiken over wat prioritaire datasets precies zijn, en waarom ze prioritair zijn

**Comment by wboersma** [comment]
Tekst herschreven zie 3.3 Prioritaire datasets
