### ISSUE TITLE
Werkwijze overzetten wiki naar Github

### ISSUE THREAD

**Issue by fhb1990** [Geonovum/inspire-wiki#2]
De wiki is overgezet vanuit https://wiki.geonovum.nl/ naar GitHub. De informatie die is overgezet is de informatie die te vinden is via de menubalk aan de rechterzijde van de wiki, plus alle pagina's waar vanuit daar naar kan worden doorgeklikt. 

Er blijken echter nog veel meer wiki-pagina's te zijn, waarvan veel verouderd. Als je bij de wiki op `random page` klikt, dan kom je veel informatie tegen die niet is overgezet. De vraag is of hier nog relevante informatie voor de huidige wiki op Github tussen staat.

**Comment by wboersma** [comment]
Overzetting heeft al plaatsgevonden.
