### ISSUE TITLE
Het hoofdstuk "Publiceren" gaat alleen maar over metadata

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/inspire-wiki#22]
Het hoofdstuk "Publiceren" gaat alleen maar over metadata. Dan past het beter onder het hoofdstuk over metadata, of ook andere vormen van publiceren moeten hier genoemd worden, zoals via services en applicaties/viewers die die aanroepen.

**Comment by idevisser** [comment]
is idd logischer om bij metadata op te nemen

**Comment by idevisser** [comment]
is verplaatst
