### ISSUE TITLE
Samenvatting, status, conformiteit

### ISSUE THREAD

**Issue by fhb1990** [Geonovum/inspire-wiki#3]
Het document opent met een samenvatting, status en conformiteit. Deels wordt dit automatisch gegenereerd vanuit de instellingen. Er moet gekeken worden naar hoe dit wenselijk wordt ingericht.

**Comment by wboersma** [comment]
Hoofdstuk 1 Conformiteit snap ik niet waarom die is opgenomen. Moeten we dit hoofdstuk opnemen?

**Comment by PB-GNM** [comment]
Ik snap ook niet wat het nut van dit hoofdstuk is. Wat mij betreft kan die er uit. Volgens mij kan dat door het volgende stuk uit de index.html halen:

  <section id="conformance">
    
  </section>

Bij de samenvatting kunnen we denk ik volstaan met een opmerking dat dit document de vervanger is van de oude wiki.
Ik heb daarvoor het md document smenvatting.md gemaakt net als dat in andere Respec documenten werkt.
Als het document af is kan hier nog een kleine opsomming bij van alle hoofdonderwerpen die er behandeld zijn.

Voor de status kunnen we denk iets vergelijkbaars doen als met de samenvatting, maar ik weet nog niet zo goed wat de status is.

**Comment by wboersma** [comment]
Voorstel: FAQ paragrafen te laten vervallen en de teksten opnemen (voor zover van toepassing) bij de andere paragrafen in het betreffende hoofdstuk

**Comment by idevisser** [comment]
eens dat FAQ bij de teksten over het onderwerp worden opgenomen.

**Comment by idevisser** [comment]
conformiteitshoofdstuk is er volgens mij nu al uit, lijkt me oke zo

**Comment by idevisser** [comment]
De teksten in samenvatting en status nog wel bewerken, bij samenvatting graag doel en doelgroep van het document opnemen, meer zoals in de introductie.  Dan wellicht introductie ook herschrijven, zodat er niet te veel overlap in zit.

**Comment by idevisser** [comment]
ook voor metadata de FAQ in tekst opgenomen
