### ISSUE TITLE
Checklist dataharmonisatie; graag jullie advies

### ISSUE THREAD

**Issue by wboersma** [Geonovum/inspire-wiki#30]
Als ik de de checklist dataharmonisatie (https://geonovum.github.io/inspire-wiki/#checklist-dataharmonisatie) lees dan vind ik het eigenlijk een bredere checklist. Het is een stappenplan van alle stappen die je moet doen om INSPIRE data geharmoniseerd te publiceren. Is het niet logischer om hier een apart hoofdstuk van te maken met als titel Checklist na het hoofdstuk Validatie?
@PB-GNM, @idevisser graag jullie advies

**Comment by PB-GNM** [comment]
Ik denk dat het een goed advies is, om het in een nieuw hoofdstuk achter Validatie te plaatsen, omdat dan ook alle stappen al een keer in detail eerder beschreven zijn.

**Comment by idevisser** [comment]
lijkt me een goed plan

**Comment by wboersma** [comment]
Ik heb de checklist verplaatst naar een apart hoofdstuk (na validatie) en verwijdert als onderdeel bij hoofdstuk 3.
