### ISSUE TITLE
4.4 Spatial data services metadata -> uniformeren

### ISSUE THREAD

**Issue by wboersma** [Geonovum/inspire-wiki#34]
@idevisser Zijn de subparagrafen onder 4.4 Spatial data services metadata eigenlijk niet allemaal invulinstructies. Zo ja, dan wil ik namen van de titelparagrafen aanpassen.
Dus:
4.4.1 Invocable SDS wordt dan 4.4.1 Invulinstructie invocable SDS metadata
enz. voor 4.4.2 en 4.4.3

En zijn de templates eigenlijk geen voorbeeldbestanden? Zo ja, dan maak ik er in de tekst ook voorbeeldbestanden van (zoals bij dataset metadata en service metadata)

**Comment by idevisser** [comment]
klopt dat het invulinstructies zijn, wordt wel naar verwezen vanuit services en daarna steeds naar voorgaande paragraaf. Dat dan ok graag aanpassen

**Comment by idevisser** [comment]
templates zijn templates, moet nog checken of ze nog nodig zijn, omdat we inmiddels een update van metadata profiel hebben gehad

**Comment by wboersma** [comment]
Titels en links aangepast
