### ISSUE TITLE
NGR-screenshots

### ISSUE THREAD

**Issue by fhb1990** [Geonovum/inspire-wiki#4]
In de wiki worden screenshots van het oude NGR gebruikt om e.e.a. aan te duiden. Deze zouden vervangen kunnen worden door screenshots van de nieuwste versie van het NGR. De noodzaak daarvan ligt ook aan of het proces dat beschreven wordt a.d.h.v. de screenshots inmiddels veranderd is.

**Comment by idevisser** [comment]
screenshots svp vervangen door nieuwe

**Comment by idevisser** [comment]
gedaan waar nodig
