### ISSUE TITLE
Hoofdstuk: introductie

### ISSUE THREAD

**Issue by fhb1990** [Geonovum/inspire-wiki#5]
- Hier kan een algehele introductie worden toegevoegd. Wat is INSPIRE? Wat zijn de Annexen? Wat is as-is data?
- Is het plaatje over de processtappen nog up to date?

**Comment by wboersma** [comment]
2.1 betrokken partijen verplaatsen naar 2.6 over deze wiki als een subparagraaf 2.6.4

2.3 Hier wordt verwezen naar het INSPIRE dossier op de Geonovum site voor o.a. de IR (deze staan hier echter niet meer expliciet op). Is het niet beter om naar de EU website (https://inspire.ec.europa.eu/quick-overview-implementers/57528) te verwijzen hiervoor.

2.4 Deadlines: 
- Ik zou de actualiteitsdeadline als extra kopje toevoegen. Nu valt het een beetje weg. Daarnaast de tekst aanpassen, dit geldt voor alle datasets zowel as-is als geharmoniseerd.
- Moet SDS niet nog als deadline worden opgevoerd?

2.5 Hier staat alleen een kopje en mist de aanvullende tekst. Deze nog toevoegen en ook updaten, zie https://wiki.geonovum.nl/index.php?title=Bronnen

2.6.3 INSPIRE Helpdesk: naam veranderen in Kenniscentrum INSPIRE. Hierbij verwijzen naar:
- INSPIRE community forum op PDOK: https://geoforum.nl/c/standaarden/inspire
- de Europese INSPIRE Helpdesk (nu incl. INSPIRE community forum): https://github.com/INSPIRE-MIF/
- de helpdesk INSPIRE (inspire@geonovum.nl) niet meer specifiek benoemen? We willen juist dat de dataproviders meer elkaar helpen ipv de helpdesk te mailen
- INSPIRE programmabureau veranderen in INSPIRE op de website van Geonovum

**Comment by wboersma** [comment]
> * Hier kan een algehele introductie worden toegevoegd. Wat is INSPIRE? Wat zijn de Annexen? Wat is as-is data?
HIER ZOU IK VERWIJZEN NAAR INSPIRE OP DE GEONOVUM WEBSITE
> * Is het plaatje over de processtappen nog up to date?
IK ZIE GEEN PLAATJE MET PROCESSTAPPEN

**Comment by idevisser** [comment]
aanpassingen  zoals hierboven opgesomt door pieter oke
daarnaast 2.5 update van de bronnen oke
in 2.6 de helpdesk bij ons toch wel noemen

De intro aanpassen, zou wel kort iets over wat is INSPIRE opnemen, ook wat as is is...de intro afstemmen op wat er in samenvatting wordt opgenomen, dus niet te veel overlap.

Denk dat we eens kritisch naar de processtappen moeten kijken. aanmerken daar iig aan toevoegen, valt n onder inrichten organisatie zou het aanmerken als aparte proces stap opnemen. Vraag me af of we nog wat over het inrichten organisatie moeten zeggen....

**Comment by wboersma** [comment]
Procesplaatje nog aanpassen. Documenten eruit en ook de best practises

**Comment by wboersma** [comment]
Dit hoofdstuk is wat mij betreft klaar
