### ISSUE TITLE
Hoofdstuk: inrichten organisatie

### ISSUE THREAD

**Issue by fhb1990** [Geonovum/inspire-wiki#6]
- Er ontbreekt een introductie bij dit hoofdstuk.
- Het is wellicht verstandig annex-informatie in die introductie te zetten.
- De paragraaf over het namespaceregister zou wat meer toelichting over namespaces kunnen gebruiken.

**Comment by wboersma** [comment]
Paragraaf 3.5 Namespaceregister onderbrengen bij dataharmonisatie. Dit is een logischere plek. H3 dan geheel wenden aan INSPIRE in Nederland: het proces van aanmerken (misschien ook betere titel)

**Comment by wboersma** [comment]
Informatie over het aanmerken en aanmerkingsproces is vrij uitgebreid. Voorstel is om deze informatie in te korten en meer te bundelen.
Daarnaast de vraag of het onderdeel rollen (3.1.1) en aandachtspunten(3.1.2) nu nog van belang zijn. Mijn voorstel is om deze informatie achterwege te laten.

**Comment by idevisser** [comment]
ok om rollen en aandachtspunten niet meer op te nemen.
namespaceregister past idd  beter onder harmonisatie

**Comment by PB-GNM** [comment]
Oké om namespaceregister naar hoofdstuk dataharmonisatie te verplaatsen, maar waar staat het register tegenwoordig eigenlijk?

**Comment by wboersma** [comment]
https://inspirelab.geonovum.nl/namespaces/ 

(maar ik heb het gevoel dat de server eruit ligt; vraag ik na bij Thijs)

**Comment by wboersma** [comment]
Alle punten verwerkt. Issue wordt gesloten.
