### ISSUE TITLE
Hoofdstuk: dataharmonisatie

### ISSUE THREAD

**Issue by fhb1990** [Geonovum/inspire-wiki#7]
- In de laatste regel van de eerste tabel (hfst 4.1): is dit nog steeds *approved* en *draft*? **PB:** de extensies zijn niet approved, dus zo gelaten
- Spatial ETL: zijn de ETL-tools nog up to date? **PB:** Alle links werken nog
- In 'welke optie toepassen?' gaat het over de 'spin-off'. Dit wordt verder niet toegelicht. Wat wordt hiermee bedoeld? **PB:** iets aangepast zodat duidelijk is over welke spin of het gaat
- 'as-is versus geharmoniseerd': Dit behoeft een inleiding. Waar gaat dit over en waarom wordt dit verteld?
- 'Prioritaire datasets' kan een inleiding gebruiken over wat prioritaire datasets precies zijn, en waarom ze prioritair zijn.
- Het URI-hoofdstuk linkt naar een 'aanzet tot nationale URI-strategie'. Is er inmiddels meer dan een aanzet? **PB:** Voor zover bekend nog niet.
- Bij 'codelijsten' moet een paragraaf worden toegevoegd over het nieuwe nationale codelijstregister.
- 'Portrayal': de term 'layer definition' moet geïntroduceerd worden. Daarnaast is deze hele paragraaf wat vaag. **PB:** De term is vervangen door: 'Het hoofdsuk protrayal in de dataspecificaties'
- Het wiki-hoofdstuk 'Control Panel' is weggelaten, omdat het niet meer relevant is.

**Comment by wboersma** [comment]
Paragraaf over namespaceregister (3.5) hier opnemen.

**Comment by wboersma** [comment]
Paragraaf 4.1: 
- check alle links. Bijv. GCM is aangepast, doorverwijzen naar: https://inspire.ec.europa.eu/documents/inspire-generic-conceptual-model
- Moet O&M hier ook niet toegevoegd worden?
- Moeten hier ook nog verwijzen naar de Good Practises?

**Comment by wboersma** [comment]
- 

-

**Comment by wboersma** [comment]
4.9 Portrayal
- Is het niet logischer om deze paragraaf op te nemen bij de viewservice omdat het om de inhoudelijke beschrijving van de viewservice gaat?
- Layer organisation: wat bedoel je met aggregation? Betekent dit volgorde.
- Symbols

**Comment by wboersma** [comment]
4.10 Geometrie
-  Europese INSPIRE-validatieservice link werkt niet. Niet logischer om naar het validatiehoofdstuk te verwijzen hier. Dan hoef je als links wijzigen het alleen in het validatie hoofdstuk aan te passen.
- In de zin "Deze validatie test niet alleen de geometrie, maar ook het applicatieschema." welk applicatieschema wordt hier bedoeld?
- Daaronder staat dat je ook dat je alleen de geometrie kunt valideren. Hier worden voorbeelden genoemd, maar geen links opgenomen. Vraag: is het verstandig om alleen de geometrie te valideren? En zo ja, is het dan niet handiger om ook links op te nemen naar de tooling?
- In de zin "Naast de geometrische benadering van 'valide objecten' zijn er ook specifieke regels voor bepaalde thema's." Wat wordt hiermee bedoeld, welke specifieke regels? Zijn dit de regels die in de twee subparagrafen er onder worden beschreven? Zo ja, dan zou ik de zin iets uitbreiden en de specifieke regels even aangegeven.

4.10.1 Aansluitende netwerken
- Officieel heten de transportnetwerken in het Nederlands Vervoersnetwerken. Dus dit aanpassen in de tekst.
- Ik zou nog even aangeven in welke paragraaf of misschien annex van de dataspec dit verder is uitgewerkt. 
- En geldt dit ook grensoverschrijdend? Of wordt dat in de volgende paragraaf uitgewerkt?

4.10.2 Cross-boundary harmonisatie
- Ook hier de Nederlandse thema namen aanhouden, dus vervoersnetwerken.
- Nog vraag/opmerking: ik weet dat hierover contact is geweest met België. Moeten we hierover nog iets opnemen? 
- Annex B van D2.6 nog hyperlinken naar paragraaf 4.1 voor het juiste document
- Aparte bullet maken vanaf de zin "De dataspecificaties van de andere thema's....
- aparte bullet maken vanaf de zin "Ook het thema Transport Networks...." En aangeven wat hier dan specifiek speelt.

**Comment by wboersma** [comment]
4.11 Datavalidatie
Is het niet logischer om alle validatie in 1 hoofdstuk te beschrijven. Dus deze paragraaf te verplaatsen naar hoofdstuk 8.

**Comment by wboersma** [comment]
4.12 Checklist dataharmonisatie: Eigenlijk is dit meer een algemene checklist hoe je INSPIRE data moet ontsluiten. Misschien een apart hoofdstuk van maken met checklist of stappenplan (in een visueel schema misschien) en dan verwijzen naar de juiste hoofdstukken/paragrafen van de wiki.

**Comment by wboersma** [comment]
4.13 Extensies:
- Is het niet logischer om dit bij paragraaf 4.3 fasen onder te brengen. Daar besteed je aandacht aan de verschillende mogelijkheden van harmonisatie. Mappen of extended, waarbij je ook meteen kunt verwijzen naar de rijk en armscenario. 
- Ik zou nog iets meer uitleggen waarom extended ook een goede optie is. Dan mist nu in de wiki. 
- De link naar de nuttige pagina op het INSPIRE community forum over het uitbreiden van codelijsten is niet meer werkzaam. Dus of weghalen of in het archief de juiste link toevoegen. Daarnaast vroeg ik me af of dit stukje niet bij de codelijsten moet, nu we een NLs codelijstregister hebben.

**Comment by wboersma** [comment]
4.14 INSPIRE community forum:
Apart hoofdstuk wijden aan de INSPIRE community (zoals we ook besproken hebben tijdens het INSPIRE operationeel overleg):
- NL INSPIRE wiki (nu nog: https://wiki.geonovum.nl/index.php/Aan_de_slag_met_INSPIRE; krijgt deze straks nieuwe URL?)
- NL INSPIRE forum (https://geoforum.nl/c/standaarden/inspire)
- EU INSPIRE community (https://github.com/inspire-mif)

**Comment by wboersma** [comment]
4.15 FAQ dataharmonisatie:
- Vraag over aanmerking verplaatsen naar hoofdstuk 3 over aanmerking .
- Vraag over wat te doen met as-is als geharmoniseerde dataset beschikbaar: Hier wordt verwezen naar een pdf die in de KBG is besproken. Deze pdf is 1:1 overgenomen in de wiki, dus ik zou alleen naar de wiki verwijzen naar paragraaf arm - rijk. Misschien moeten we deze FAQ tekst ook nog opnemen in deze arm-rijk paragraaf. Dan staat alles mooi bij elkaar. 
- Vraag over vragen, opmerkingen en verbetervoorstellen over de dataspecificaties: verwijzen naar EU INSPIRE community en dan onderdeel General.

**Comment by idevisser** [comment]
Paragraaf 4.1:

check alle links en genoemde versies. Bijv. GCM is aangepast, doorverwijzen naar: 
Moet O&M hier ook niet toegevoegd worden?->  lijkt me niet nodig
Moeten hier ook nog verwijzen naar de Good Practises? ->ja, naar die die betrekking hebben op dataharmo
PB voorstel: 2e alinea: alleen 1e 2 zinnen behouden -> alleen het stukje over placeholders eruit, lijkt m goed dat een ieder kan zien dat de specificaties al jaren beschikbaar zijn.

**Comment by idevisser** [comment]
Paragraaf 4.1: link naar data modellen aanpassen, is nu zelfde als naar data specificaties

**Comment by idevisser** [comment]
4.3.2.3 On the fly converteren: Hangt de keuze ook niet samen met de QoS verplichtingen van INSPIRE. Hierbij verwijzen naar 6.1.6 Quality of services -> ja graag naar de QoS vereisten verwijzen

**Comment by idevisser** [comment]
@Wideke, kun jij voor onderstaande de tekst aanvullen en juiste verwijzing doen?

4.5 Prioritaire datasets (e-reporting).
-Dit stuk aanvullen met de nieuwe ontwikkelingen en verwijzen naar de nieuwe actie: https://webgate.ec.europa.eu/fpfis/wikis/display/InspireMIG/Action+2.1+Need-driven+data+prioritisation
-PB: Wat wordt bedoeld met "en voor as-is versus nieuwe datasets"?
-PB: Huidige link achter JRC linkt door naar Inspire helpdesk. Waar naartoe aanpassen?

**Comment by PB-GNM** [comment]
Alles is verwerkt, behalve de opmerkingen over prioritaire datasets.
Daar is een nieuw issue van gemaakt. #17
