### ISSUE TITLE
Hoofdstuk: metadata

### ISSUE THREAD

**Issue by fhb1990** [Geonovum/inspire-wiki#8]
- Moet dit hoofdstuk niet 'dataset-metadata' heten? Service-metadata wordt namelijk pas behandeld in het hoofdstuk 'services'.
- Er moet een algemene metadata-introductie komen.
- In 'Eisen metadata' wordt over 'onder conditie verplicht' gesproken. Wat betekent dit? Dit moet geïntroduceerd en toegelicht worden.
- 'Gebruikersvoorwaarden in Nederland': bestaat Geogedeeld nog? De licensegenerator is in ieder geval offline.
- Bij de invulinstructietabel ontbreekt bij sommige rijen het veld 'omschrijving'.
- De tekst bij 'aandachtspunten' onder deze tabel is erg onduidelijk. Wat wordt hier bedoeld?
- 'Prioritaire datasets': hier wordt iets gezegd over overgaan naar metadataprofiel 2.0. Moet hierdoor hier inmiddels iets gewijzigd worden?

**Comment by wboersma** [comment]
- Ik zou alle metadata bij elkaar plaatsen dus ook hier aandacht besteden aan de service metadata. 
- Daarnaast zou ik zo veel mogelijk verwijzen naar de metadata wiki ipv in deze wiki op te nemen (bijv. 4.6 Invulinstructies voor datasets; dit staat ook op de andere wiki)
- Vraag: voor de prioritaire datasets zijn nu twee scenario's uitgewerkt op de wiki. Is scenario 1 nog logisch met het verplicht gebruik van MD v2 profiel? Zo nee, dit dan weghalen.

**Comment by idevisser** [comment]
punten aangepast waar mogelijk.
De invulinstructies die hier zijn opgenomen zijn INSPIRE specifiek, dus geen onderdeel van het NL profiel. In het nl profiel worden vooral de elementen vastgelegd, het invullen daarbuiten laten zodat het flexibeler is en er geen profielaanpassing nodig is met procedure.
