### ISSUE TITLE
Hoofdstuk: services

### ISSUE THREAD

**Issue by fhb1990** [Geonovum/inspire-wiki#9]
- Er moet een introductie komen. **PB:** toegevoegd
- Bij networkservices werd oorspronkelijk naar het INSPIRE Domain Model gerefereerd. Is dit nog relevant?  Waar Zoekopdrachten leveren alleen een document uit 2010 op, en onze eigen wiki. Zo ja, dan kan dit nog worden toegevoegd. In dat geval kunnen de volgende pagina's gebruikt worden: 

https://wiki.geonovum.nl/index.php?title=Het_INSPIRE_Domain_Model
https://wiki.geonovum.nl/index.php?title=Het_INSPIRE_Domain_Model_en_geharmoniseerde_fysieke_datasets
https://wiki.geonovum.nl/index.php?title=Oorspronkelijk_Domain_model
https://inspire.ec.europa.eu/documents/Network_Services/INSPIRE%20Domain%20Model%20v0.9.1.pdf
**PB:** Verwerkt in inleidende stukje.
- Kopje 'registerdiensten' bij paragraaf 'Network services': dit lijkt me erg verouderd. **PB:** Aangepast
- Sowieso kan de hele paragraaf 'Network services' worden gecheckt op actualiteit. **PB:** Gedaan
- 'Rights-management layer': is dit verouderd? 'Op dit moment van schrijven' is 2010... **PB:** Iets aangepast, maar niet zeker of dat voldoende is.
- Ik heb steeds bij services pagina's over 'recente wijzigingen' achterwege gelaten, omdat die uit 2011-2013 kwamen en dus niet meer recent waren. **PB:** OKé
- Ergens wordt verwezen naar een UUID-hoofdstuk, wat nu niet in de wiki staat. Het gaat om deze wiki-entry: https://wiki.geonovum.nl/index.php?title=UUID,_NEN3610ID . Deze informatie zou nog toegevoegd kunnen worden. **PB:** Apart issue van gemaakt https://github.com/Geonovum/inspire-wiki/issues/19
- Viewservice FAQ rept over: we zien verder in 2013. Dit moet up to date gemaakt worden. **PB:** Alle FAQ antwoorden op gewenste locatie verdeeld.
- Downloadservices moeten een introductie krijgen. **PB:** toegevoegd
- In de oude wiki werd een opensearch-voorbeeld gegeven die verouderd was (dode links), die is nu weggelaten. Misschien kan er een nieuw voorbeeld worden toegevoegd.**PB:** Wat niet werkte is aangepast.
- Op de wiki staat over WFS veel minder informatie dan over WMS, bijvoorbeeld geen informatie over capabilities-elementen terwijl dat bij WMS erg uitgebreid is. **PB:** In de inleiding van WFS direct access is toegelicht waarom. 
- WCS- en SOS- informatie zou wat uitgebreid kunnen worden.**PB:** Ik stel voor dat we eerst zorgen dat de huidige versie actueel is en later pas aanvullingen doen. Ik heb OAF toegevoegd en FAQ weer verdeeld over de rest.
- De tabelplaatjes in het SDS-hoofdstuk kunnen worden overgezet naar echte tabellen. **PB:** Dit is geen onderdeel meer van het hoofdstuk Services
-

**Comment by wboersma** [comment]
Good Practises toevoegen

**Comment by PB-GNM** [comment]
paragraaf 5.3:Download service: https://inspire.ec.europa.eu/documents/technical-guidance-implementation-inspire-download-services als link toevoegen

**Comment by PB-GNM** [comment]
paragraaf 5.3.4.1: Verhouding Nederlandsprofiel: https://www.geonovum.nl/geo-standaarden/services/nederlands-wfs-profiel-11-op-iso-19142-voor-web-feature-services-20 als link toevoegen

**Comment by PB-GNM** [comment]
Is het al tijd voor het opnemen van een hoofdstukje over OGC API Features als download?

**Comment by PB-GNM** [comment]
5.1 Moet hier niet uitgelegd worden wat wordt bedoeld met een "Network service". Waar vinden we een goede definitie?
5.1.2 en 5.1.6.1 Wetgevingslink (L274) geeft iets over groene en fruit?
5.1.3 Versienummers weghalen en alleen link naar locatie document. => altijd laatste
5.1.7 Wie heeft er kennis om dit te beoordelen?
5.2 Het is onduidelijk wat een "INSPIRE Link View Service " is
5.2.1 Wat is CRS:84? WGS84 staat er al bij
5.2.2 Noem bij 1e scenario ook dat de INSPIRE vereiste metadata in een CSW zit zoals NGR
5.2.2.1 Voorbeeld: anders dan bij PDOK. Is dat erg?
5.2.2.2 Wordt scenario 2 eigenlijk wel gebruikt? Wanneer kies je voor 1 en wanneer voor 2
5.2.4 Engelse voorbeeld: wat zou hier in NL dan anders zijn?
5.2.5 ZIP bestanden verplaatsen naar https://github.com/Geonovum/inspire-wiki/tree/main/docs
5.2.6 FAQ Laatste vraag: is doc "Wat te doen bij wijzigingen" nog actueel?
5.3.1.2.1 3 optie: Wat is een XPATH?
5.3.2 link opensearch werkt niet meer+> alleen root opnemen?
5.3.2.1 t/m 4 Misschien te veel detail en bovendien niet duidelijk wat de termen betekenen. Voorstel: doorverwijzen naar de technical guidance?
5.3.3.3.2 laatste zin in alinea na 1e opsomming: "hoeven te" -> "zullen"
5.4.2 zip bestand verplaatsen naar https://github.com/Geonovum/inspire-wiki/tree/main/docs
5.5.2 xml's verplaatsen naar https://github.com/Geonovum/inspire-wiki/tree/main/docs
5.4 en 5.5.2 verplaatsen naar hoofdstuk over metadata

**Comment by PB-GNM** [comment]
Alles is verwerkt, of er is een apart issue van gemaakt.
